/**
 * Representative Topic Engine T0 fixture used by the migration integration
 * tests. All values are synthetic; Chinese strings are intentional to prove
 * utf8mb4 round-trips. JSON strings are stored as compact JSON for the raw-SQL
 * baseline path and as parsed objects for the Prisma Client path.
 */
import { sha256, uuid } from './helpers.js';

export const T0_IDS = {
  syncJob: uuid(),
  snapshot: uuid(),
  cat: uuid(),
  media: uuid(),
  trend: uuid(),
  reference: uuid(),
  pattern: uuid(),
  opportunity: uuid(),
  candidate: uuid(),
  scoreRun: uuid(),
  audit: uuid(),
} as const;

export const T0_FIXTURE = {
  syncJob: {
    id: T0_IDS.syncJob,
    tenant_id: 'bangcat',
    mode: 'manual-fixture',
    status: 'finished',
    started_at: '2026-07-21 10:00:00.000',
    finished_at: '2026-07-21 10:01:00.000',
    read_count: '1',
    inserted_count: '1',
    updated_count: '0',
    unchanged_count: '0',
    error_count: '0',
    error_summary: null,
  },
  snapshot: {
    id: T0_IDS.snapshot,
    tenant_id: 'bangcat',
    source_id: 'cat-pocket-001',
    sync_job_id: T0_IDS.syncJob,
    source_updated_at: '2026-07-21 09:00:00.000',
    source_hash: sha256('cat-pocket-001'),
    sanitized_json: JSON.stringify({ name: '裤兜', breed: '中华田园猫' }),
    issues_json: JSON.stringify(['removed rescuerPhone']),
    synced_at: '2026-07-21 10:00:30.000',
  },
  cat: {
    id: T0_IDS.cat,
    tenant_id: 'bangcat',
    source_id: 'cat-pocket-001',
    name: '裤兜',
    sex: '公猫',
    approximate_age_months: '18',
    breed: '中华田园猫',
    coat_color: '狸花白',
    adoption_status: '待领养',
    public_description: '有点胆小，但熟悉后会主动靠近人。',
    public_rescue_story: '在街边被发现后进入猫站。',
    public_personality_notes: '喜欢听音乐，也喜欢追逗猫棒。',
    source_updated_at: '2026-07-21 09:00:00.000',
    source_hash: sha256('cat-pocket-001'),
    is_public: '1',
    completeness_score: '80',
    created_at: '2026-07-21 10:00:31.000',
    updated_at: '2026-07-21 10:00:31.000',
  },
  media: {
    id: T0_IDS.media,
    tenant_id: 'bangcat',
    cat_asset_id: T0_IDS.cat,
    source_media_id: 'media-001',
    source_url: 'https://example.com/cats/kudou.jpg',
    storage_key: null,
    kind: 'image',
    usage_scope: 'public',
    alt_text: '狸花白猫坐在窗台上',
    content_hash: sha256('media-001'),
    created_at: '2026-07-21 10:00:32.000',
    updated_at: '2026-07-21 10:00:32.000',
  },
  trend: {
    id: T0_IDS.trend,
    tenant_id: 'bangcat',
    signal_type: 'platform-topic',
    title: '猫咪的反差萌瞬间',
    description: '高冷猫突然撒娇的反差内容互动率高。',
    platform: 'xiaohongshu',
    signal_strength: '0.8123',
    starts_at: '2026-07-20 00:00:00.000',
    expires_at: '2026-08-20 00:00:00.000',
    source_url: 'https://example.com/trends/contrast-cats',
    metadata_json: JSON.stringify({ region: 'cn', windowDays: 30 }),
    status: 'active',
    created_by: 'operator-1',
    updated_by: null,
    created_at: '2026-07-21 11:00:00.000',
    updated_at: '2026-07-21 11:00:00.000',
  },
  reference: {
    id: T0_IDS.reference,
    tenant_id: 'bangcat',
    platform: 'xiaohongshu',
    url: 'https://example.com/notes/contrast-cat-viral',
    url_hash: sha256('https://example.com/notes/contrast-cat-viral'),
    title: '高冷猫今天主动蹭我了',
    summary: '爆款案例：以反差为核心的三段式叙事，只记录抽象结构。',
    metrics_json: JSON.stringify({ likes: 120000, comments: 5300 }),
    published_at: '2026-07-10 08:00:00.000',
    captured_at: '2026-07-21 11:05:00.000',
    status: 'approved',
    created_by: 'operator-1',
    updated_by: null,
    created_at: '2026-07-21 11:05:00.000',
    updated_at: '2026-07-21 11:05:00.000',
  },
  pattern: {
    id: T0_IDS.pattern,
    tenant_id: 'bangcat',
    name: '反差萌三段式',
    category: 'emotional-contrast',
    hook_pattern: '先展示高冷日常，再给出意外撒娇瞬间。',
    narrative_structure_json: JSON.stringify(['setup-distance', 'unexpected-warmth', 'call-to-adopt']),
    emotion_curve_json: JSON.stringify({ start: 'calm', peak: 'surprise', end: 'warm' }),
    visual_grammar_json: JSON.stringify({ shots: ['wide-alone', 'close-up-headbutt'] }),
    interaction_mechanism: '评论区征集同款反差瞬间。',
    prohibited_elements_json: JSON.stringify(['不复制原文措辞', '不模仿连续镜头']),
    status: 'approved',
    created_by: 'operator-1',
    updated_by: null,
    created_at: '2026-07-21 11:10:00.000',
    updated_at: '2026-07-21 11:10:00.000',
  },
  patternLink: {
    tenant_id: 'bangcat',
    pattern_id: T0_IDS.pattern,
    reference_content_id: T0_IDS.reference,
    created_at: '2026-07-21 11:11:00.000',
  },
  opportunity: {
    id: T0_IDS.opportunity,
    tenant_id: 'bangcat',
    cat_asset_id: T0_IDS.cat,
    opportunity_type: 'story-angle',
    summary: '裤兜从胆小到亲人的转变适合做反差叙事。',
    unique_facts_json: JSON.stringify(['救助后三周才主动靠近人']),
    available_assets_json: JSON.stringify(['近照 3 张', '猫站日常视频 1 段']),
    business_goals_json: JSON.stringify(['提升领养咨询', '积累小红书粉丝']),
    valid_until: '2026-09-30 00:00:00.000',
    status: 'active',
    created_by: 'operator-1',
    updated_by: null,
    created_at: '2026-07-21 11:20:00.000',
    updated_at: '2026-07-21 11:20:00.000',
  },
  candidate: {
    id: T0_IDS.candidate,
    tenant_id: 'bangcat',
    cat_asset_id: T0_IDS.cat,
    platform: 'xiaohongshu',
    format: 'image-text',
    content_level: 'fact-based',
    premise: '一只三周不肯靠近人的猫，今天把头塞进了我的口袋。',
    audience_reason: '反差萌加领养主题在当前趋势下互动意愿高。',
    hook: '它用了 21 天，才决定相信我。',
    story_beats_json: JSON.stringify(['初遇躲避', '渐进信任', '口袋撒娇']),
    fact_source_ids_json: JSON.stringify([T0_IDS.snapshot]),
    asset_requirements_json: JSON.stringify(['口袋特写', '窗台远照']),
    originality_constraints_json: JSON.stringify(['不复刻参考案例分镜']),
    signals_json: null,
    score_json: null,
    total_score: null,
    score_decision: null,
    score_version: null,
    status: 'draft',
    created_by: 'operator-1',
    updated_by: null,
    created_at: '2026-07-21 11:30:00.000',
    updated_at: '2026-07-21 11:30:00.000',
  },
  candidateTrendLink: {
    tenant_id: 'bangcat',
    topic_candidate_id: T0_IDS.candidate,
    trend_signal_id: T0_IDS.trend,
  },
  candidatePatternLink: {
    tenant_id: 'bangcat',
    topic_candidate_id: T0_IDS.candidate,
    viral_pattern_id: T0_IDS.pattern,
  },
  scoreRun: {
    id: T0_IDS.scoreRun,
    tenant_id: 'bangcat',
    topic_candidate_id: T0_IDS.candidate,
    signals_json: JSON.stringify({ trendFit: 0.8, catMatch: 0.9 }),
    result_json: JSON.stringify({ total: 0.76, decision: 'keep', hardBlocks: [] }),
    scoring_version: 't0-v1',
    created_by: 'operator-1',
    created_at: '2026-07-21 11:35:00.000',
  },
  audit: {
    id: T0_IDS.audit,
    tenant_id: 'bangcat',
    request_id: 'req-fixture-001',
    actor_type: 'user',
    actor_id: 'operator-1',
    action: 'topic.candidate.create',
    entity_type: 'topic_candidate',
    entity_id: T0_IDS.candidate,
    metadata_json: JSON.stringify({ via: 'migration-test-fixture' }),
    created_at: '2026-07-21 11:36:00.000',
  },
} as const;

/** Maps fixture keys to committed-migration table names in FK-safe insert order. */
export const T0_TABLE_ORDER: Array<[table: string, rows: Array<Record<string, string | null>>]> = [
  ['source_sync_jobs', [T0_FIXTURE.syncJob]],
  ['source_cat_snapshots', [T0_FIXTURE.snapshot]],
  ['cat_assets', [T0_FIXTURE.cat]],
  ['cat_media_assets', [T0_FIXTURE.media]],
  ['trend_signals', [T0_FIXTURE.trend]],
  ['reference_contents', [T0_FIXTURE.reference]],
  ['viral_patterns', [T0_FIXTURE.pattern]],
  ['pattern_source_links', [T0_FIXTURE.patternLink]],
  ['cat_content_opportunities', [T0_FIXTURE.opportunity]],
  ['topic_candidates', [T0_FIXTURE.candidate]],
  ['topic_candidate_trends', [T0_FIXTURE.candidateTrendLink]],
  ['topic_candidate_patterns', [T0_FIXTURE.candidatePatternLink]],
  ['topic_score_runs', [T0_FIXTURE.scoreRun]],
  ['audit_logs', [T0_FIXTURE.audit]],
];
